- name: backend
  hosts: all
  become: true
  tasks:

    - name: remove old nodejs module
      ansible.builtin.shell: dnf module disable nodejs -y

    - name: enable new nodejs module
      ansible.builtin.shell: dnf module enable nodejs:20 -y

    - name: Install nodejs
      ansible.builtin.dnf:
        name: nodejs
        state: installed

    - name: Add expense user
      ansible.builtin.user:
        name: expense

    - name: remove old app dir
      ansible.builtin.file:
        path: /app
        state: absent

    - name: add a app dir
      ansible.builtin.file:
        path: /app
        state: directory

    - name: download backend contents
      ansible.builtin.unarchive:
        src: https://expense-artifacts.s3.amazonaws.com/expense-backend-v2.zip
        dest: /app
        remote_src: yes

    - name: Download dependencies
      community.general.npm:
        path: /app
        state: latest

    - name: Copy backend service file
      ansible.builtin.copy:
        src: backend.service
        dest: /etc/systemd/system/backend.service

    - name: Install mysql
      ansible.builtin.pip:
        name:
        - PyMySQL
        - cryptography
        executable: pip3.9

    - name: load schema
      community.mysql.mysql_db:
        state: import
        name: all
        target: /app/schema/backend.sql
        login_user: root
        login_password: ExpenseApp@1
        login_host: mysql-dev.pappik.online


    - name: systemd service
      ansible.builtin.systemd:
        name: backend
        enabled: yes
        daemon_reload: true
        state: restarted