- name: mysql
  hosts: all
  become: true
  tasks:
    - name: Install mysql
      ansible.builtin.dnf:
        name: mysql-server
        state: installed

    - name: Start service httpd, if not started
      ansible.builtin.service:
        name: mysqld
        state: started
        enabled: yes

    - name: Change root passwd
      ansible.builtin.shell: mysql_secure_installation --set-root-pass ExpenseApp@1
