- name: Install mysql
  ansible.builtin.dnf:
    name: mysql-server
    state: installed

- name: enable and start mysql
  ansible.builtin.systemd_service:
    name: mysqld
    state: started
    enabled: yes

- name: Change mysql root passwd
  ansible.builtin.shell: mysql_secure_installation --set-root-pass ExpenseApp@1
