format_version: 10
pipelines:
  backend:
    group: defaultGroup
    materials:
      git-1d0caff:
        git: https://github.com/iteration-1/ansible-expense.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
      - DEV:
          fetch_materials: true
          environment_variables:
            env: dev
          approval:
            type: manual
          jobs:
            ansible-playbook:
              tasks:
                - exec:
                    arguments:
                      - ansible.sh
                      - backend
                    command: bash
                    run_if: passed
      - QA:
          fetch_materials: true
          approval:
            type: manual
          jobs:
            ansible-playbook:
              tasks:
                - exec:
                    arguments:
                      - ansible.sh
                      - backend
                    command: bash
                    run_if: passed
      - STAGE:
          fetch_materials: true
          approval:
            type: manual
          jobs:
            ansible-playbook:
              tasks:
                - exec:
                    arguments:
                      - ansible.sh
                      - backend
                    command: bash
                    run_if: passed

      - PROD:
          fetch_materials: true
          approval:
            type: manual
          jobs:
            ansible-playbook:
              tasks:
                - exec:
                    arguments:
                      - ansible.sh
                      - backend
                    command: bash
                    run_if: passed
